let products = [
    {
        id: 1,
        title: "Apple Headphone",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Apple Headphone.jpg",
        price: 55,
        quntity: 1,
    },
    {
        id: 2,
        title: "Blue Aviator",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Blue Aviator.webp",
        price: 15,
        quntity: 1,
    },
    {
        id: 3,
        title: "Bluetooth Earphones",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Bluetooth Earphones.png",
        price: 45,
        quntity: 1,
    },
    {
        id: 4,
        title: "Closeup Of A Pocket",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Closeup Of A Pocket .webp",
        price: 35,
        quntity: 1,
    },
    {
        id: 5,
        title: "Collection Watch",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Collection Watch.jpg",
        price: 25,
        quntity: 1,
    },
    {
        id: 6,
        title: "Computer Course",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Computer Course.webp",
        price: 155,
        quntity: 1,
    },
    {
        id: 7,
        title: "Cool Glasses",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Cool Glasses.jpeg",
        price: 17,
        quntity: 1,
    },
    {
        id: 8,
        title: "Cute Kitty",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Cute Kitty.jpg",
        price: 13,
        quntity: 1,
    },
    {
        id: 9,
        title: "Dj Earphones",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Dj Earphones.png",
        price: 49,
        quntity: 1,
    },
    {
        id: 10,
        title: "Dress Shoes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Dress Shoes.webp",
        price: 60,
        quntity: 1,
    },
    {
        id: 11,
        title: "Gaming Headphones",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Gaming Headphones.avif",
        price: 53,
        quntity: 1,
    },
    {
        id: 12,
        title: "Green Sunglasses",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Green Sunglasses.jpg",
        price: 13,
        quntity: 1,
    },
    {
        id: 13,
        title: "HP Laptop",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/HP Laptop.png",
        price: 150,
        quntity: 1,
    },
    {
        id: 14,
        title: "Laptop Dell",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Laptop Dell.png",
        price: 143,
        quntity: 1,
    },
    {
        id: 15,
        title: "Life Sunglasses",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Life Sunglasses.avif",
        price: 11,
        quntity: 1,
    },
    {
        id: 16,
        title: "Luxury Shoes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Luxury Shoes.png",
        price: 52,
        quntity: 1,
    },
    {
        id: 17,
        title: "Luxury Watch",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Luxury Watch.webp",
        price: 66,
        quntity: 1,
    },
    {
        id: 18,
        title: "Macbook",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Macbook.png",
        price: 124,
        quntity: 1,
    },
    {
        id: 19,
        title: "Nike Football",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Nike Football.jpg",
        price: 63,
        quntity: 1,
    },
    {
        id: 20,
        title: "Occhiali Minecraft",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Occhiali Minecraft.avif",
        price: 11,
        quntity: 1,
    },
    {
        id: 21,
        title: "Orginal Red",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Orginal Red.png",
        price: 70,
        quntity: 1,
    },
    {
        id: 22,
        title: "Pngtree Colorful",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Pngtree Colorful.png",
        price: 59,
        quntity: 1,
    },
    {
        id: 23,
        title: "Pngtree Headphones",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Pngtree Headphones.png",
        price: 63,
        quntity: 1,
    },
    {
        id: 24,
        title: "Pngtree Sports",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Pngtree Sports.png",
        price: 58,
        quntity: 1,
    },
    {
        id: 25,
        title: "pngtree-realistic",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/pngtree-realistic.png",
        price: 51,
        quntity: 1,
    },
    {
        id: 26,
        title: "Powerful Gaming",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Powerful Gaming.png",
        price: 187,
        quntity: 1,
    },
    {
        id: 27,
        title: "Rolex Clipart",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Rolex Clipart.jpg",
        price: 88,
        quntity: 1,
    },
    {
        id: 28,
        title: "Running Shoes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Running Shoes.avif",
        price: 69,
        quntity: 1,
    },
    {
        id: 29,
        title: "Safety Glasses",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Safety Glasses.jpg",
        price: 19,
        quntity: 1,
    },
    {
        id: 30,
        title: "Samsung Galaxy",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Samsung Galaxy.webp",
        price: 145,
        quntity: 1,
    },
    {
        id: 31,
        title: "silver Gold",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/silver Gold.avif",
        price: 78,
        quntity: 1,
    },
    {
        id: 32,
        title: "Small Laptop",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Small Laptop.png",
        price: 151,
        quntity: 1,
    },
    {
        id: 33,
        title: "Smart Watches",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Smart Watches.jpg",
        price: 89,
        quntity: 1,
    },
    {
        id: 34,
        title: "Student Isolated",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Student Isolated.avif",
        price: 164,
        quntity: 1,
    },
    {
        id: 35,
        title: "Tennis Shoes",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Tennis Shoes.avif",
        price: 69,
        quntity: 1,
    },
    {
        id: 36,
        title: "Wired Headphone",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "./asstes/Wired Headphone.jpg",
        price: 71,
        quntity: 1,
    },
];
